dubbo:
  application:
    #application-name 本模块名字
    name: springboot-zk-provider
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20880
#    host: 192.168.50.5


server:
  port: 8088